name: Generate Readme

on:
  workflow_dispatch:
  issues:
    types: [opened]

env:
  TZ: Asia/Shanghai

jobs:
  bot:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.triggering_actor
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Run Script
        run: pnpm install && pnpm build && pnpm prettier

      - name: Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          push-branch: master
          commit-message: 'Update README.md by Github Actions'
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
