name: Trigger Notes Deploy

on:
  workflow_dispatch: # 手动触发
  issues:
    types: [opened] # 创建 issue 时触发

env:
  TZ: Asia/Shanghai

jobs:
  trigger-notes-actions:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.triggering_actor
    steps:
      # 触发 github pages 构建
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ secrets.REPOSITORY }}
          event-type: build-and-deploy
